CREATE DATABASE users;
DROP TABLE IF EXISTS permissao CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;
DROP TABLE IF EXISTS token CASCADE;

CREATE TABLE usuario (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                         nome_completo VARCHAR(100) NOT NULL,
                         email VARCHAR(100) NOT NULL,
                         senha VARCHAR(100) NOT NULL,
                         foto VARCHAR(512) NOT NULL,
                         criado_em TIMESTAMP NOT NULL,
                         editado_em TIMESTAMP,
                         ativo  BOOLEAN

);
ALTER TABLE usuario ADD CONSTRAINT pk_usuario PRIMARY KEY (id);
ALTER TABLE usuario ADD CONSTRAINT uk_usuario_email UNIQUE (email);


CREATE TABLE permissao (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                           funcao VARCHAR(100) NOT NULL,
                           usuario_id BIGINT NOT NULL
);
ALTER TABLE permissao ADD CONSTRAINT pk_permissao PRIMARY KEY (id);
ALTER TABLE permissao ADD CONSTRAINT uk_permissao UNIQUE (funcao, usuario_id);
ALTER TABLE permissao ADD CONSTRAINT fk_permissao_usuario FOREIGN KEY (usuario_id) REFERENCES usuario;

CREATE TABLE token (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                           token VARCHAR(100) NOT NULL,
                           data_expiracao TIMESTAMP NOT NULL,
                           usuario_id BIGINT NOT NULL
);
ALTER TABLE token ADD CONSTRAINT pk_token PRIMARY KEY (id);
ALTER TABLE token ADD CONSTRAINT uk_token UNIQUE (usuario_id);
ALTER TABLE token ADD CONSTRAINT fk_token FOREIGN KEY (usuario_id) REFERENCES usuario;


insert into usuario (email, nome_completo, senha, foto, ativo, criado_em) values ('admin@cwi.com.br', 'admin', '$2a$10$0WIu3eSZMflwT0WS5VxygeQ.IrAOmrCIDaIElWofW149iiLQxT2Xy', 'https://m.media-amazon.com/images/I/81CSHK7umJL.jpg', TRUE, CURRENT_TIMESTAMP);
insert into usuario (email, nome_completo, senha, foto, ativo, criado_em) values ('usuario@cwi.com.br', 'usuario', '$2a$10$0WIu3eSZMflwT0WS5VxygeQ.IrAOmrCIDaIElWofW149iiLQxT2Xy', 'https://m.media-amazon.com/images/I/81CSHK7umJL.jpg',TRUE, CURRENT_TIMESTAMP);

insert into permissao (funcao, usuario_id) values ('ADMIN', 1);
insert into permissao (funcao, usuario_id) values ('USUARIO', 1);
insert into permissao (funcao, usuario_id) values ('USUARIO', 2);
