spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: 8718
  jpa:
    hibernate:
       ddl-auto: validate
  mail:
    host: smtp.gmail.com
    port: 587
    username: 1studentsucess@gmail.com
    password: axgljqszglegfknh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  error:
    include-message: always





